### ISSUE TITLE
run_kde producing vf with nan

### ISSUE THREAD

**Issue by rlittman16** [eilslabs/ssam#1]
Hello,

I am trying to use ssam on my merfish data, and am running a problem with the preprocessing step. I'm following the steps in the jupyter notebook MERFISH_POA.ipynb. After I run run_kde I have vf_sd1_bw2.5.pkl in my kde directory. I also specified a new directory so that my output is in a different place than the jupyter notebook specifies. This runs without error, but when I try and continue with finding local maxima, the plots are all flat and I find 0 local max vectors. After some digging I realized that ds.vf only has nan in it. Do you have any thoughts on this?

For run_kde I am using bandwidth = 2.5 and use_mmap=False as was done in the jupyter notebook, although I'm not sure what these parameters are for.

Thanks in advanced!

**Comment by pjb7687** [comment]
Hello, I would like to ask 2 questions:
1) Did you download all raw data using 'download_data.sh'? It already contains a precomputed KDE result, 'vf_sd1_bw2.5.pkl' file.
2) If so, could you try to load 'vf_sd1_bw2.5.pkl' in a different notebook, and see whether it contains proper values or only nans?

**Comment by rlittman16** [comment]
I did download all of the data with download_data.sh. I should have clarified. When I am going through the jupyter notebook, this data works fine, the problem is on my own data. I've made sure the format matches the test data.

**Comment by rlittman16** [comment]
This is also a RuntimeWarning message I just got that most likely contributes:

`/u/home/r/rlittman/project-rlittman/miniconda3/lib/python3.7/site-packages/ssam/__init__.py:570: RuntimeWarning: invalid value encountered in true_divide
  pdf /= np.sum(pdf)`

**Comment by pjb7687** [comment]
I see. Then could you please check whether your mRNA locations are within the range between [0, width], [0, height], [0, depth]? Sometimes, for some data I notice that mRNA locations are outside of the image area.

**Comment by rlittman16** [comment]
This worked, thank you!
