### ISSUE TITLE
Recommendations for tissues with heterogeneous cell density

### ISSUE THREAD

**Issue by rlittman16** [eilslabs/ssam#10]
Hello,

I am working with hippocampus data which have areas with extremely high cell density surrounded by areas with extremely sparse regions. Do you have any recommendations on how to deal with these areas with regards to bandwidth and other parameters?

Thanks!

**Comment by pjb7687** [comment]
Thanks for posting, actually what matters here is the average distance between the mRNA spots; if they are dense enough, we can expect that the density estimation will work well. If they are close enough, then you can try out reduced bandwidths, e.g. 2 um or even 1.5 um. If the signal is quite sparse, then unfortunately I think not many things can be done.
