### ISSUE TITLE
NameError: name 'analysis' 'np' 'plt' is not defined when running the MERFISH_POA.ipynb 

### ISSUE THREAD

**Issue by neugun** [eilslabs/ssam#11]
Hi! Really nice tool. I found the ssam is really interesting and I am a new starter with the R. When I am trying to run the MERFISH_POA.ipynb within the Jupyter notebook, there throw me serval errors while I running it.

First, NameError: name 'analysis' 'np' and 'plt' are not defined and I attached a example error below.
NameError Traceback (most recent call last)
in
1 # this requires local R installation with packages 'sctransform' and 'feather'
----> 2 analysis.normalize_vectors_sctransform()
NameError: name 'analysis' is not defined

Second, this requires local R installation with packages 'sctransform' and 'feather'. I usually conda install r-packages. but It doesn't work at this time, maybe I didn't make a successful local R installation with packages 'sctransform' and 'feather'. Do you have any suggestions for installing these packages?

Thank you so much!
Best,
Wegood

**Comment by pjb7687** [comment]
Hi, The Jupyter notebooks should be run from the first cell, not from the middle. And you will need to install all prerequisites (e.g. numpy, matplotlib, etc.) beforehand.

Best,
Jeongbin

**Comment by neugun** [comment]
Hi, Jeongbin！Thank you for your advice. The problem has been solved.
Best,
Wegood
