### ISSUE TITLE
IndexError   ds.vf[..., gidx]  

### ISSUE THREAD

**Issue by neugun** [eilslabs/ssam#12]
Hello,
I am trying to use ssam on your sample merfish data in the jupyter notebook MERFISH_POA.ipynb, and met a IndexError problem with the preprocessing step (please see below).  More specificlly, ds.vf[..., gidx] is out of bounds for axis 3 with size 0. ds Do you have any thoughts on this? Do I need to change the code?
Thanks!

 Here is my code:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-12-62fa8d887c20> in <module>
      6 for i, gidx in enumerate(gindices[:6], start=1):
      7     ax = plt.subplot(5, 2, i)
----> 8     n, bins, patches = ax.hist(ds.vf[..., gidx][np.logical_and(ds.vf[..., gidx] > 0, ds.vf[..., gidx] < viewport)], bins=100, log=True, histtype=u'step')
      9     ax.set_xlim([0, viewport])
     10     ax.set_ylim([n[0], n[-1]])
IndexError: index 94 is out of bounds for axis 3 with size 0
----------------------------
File "D:\Anaconda3\envs\ssam\lib\site-packages\ssam\__init__.py", line 662, in find_localmax
 exp_mask |= self.dataset.vf[..., i] > min_expression
IndexError: index 0 is out of bounds for axis 3 with size 0

![image](https://user-images.githubusercontent.com/26133490/79724982-0c2f3f00-831b-11ea-8c9d-5911e3611995.png)

**Comment by yichunher** [comment]
Hi, I met the same error! Did you solve it?
Thanks!

**Comment by pjb7687** [comment]
Hi, The index 3 of the vector field, `vf`, is for the genes. I would like to suggest checking the shape of `ds.vf` array, and the size of the index 3 matches with the number of genes.
