### ISSUE TITLE
work environments package version

### ISSUE THREAD

**Issue by lidanwu** [eilslabs/ssam#16]
Here there, 
I'm trying to run Jupyter notebook in my laptop and I keep running into failure of import library. 
Could you please share the version info of all packages required?
For example, I notice that sklearn.neighbors.kde has been changed to sklearn.neighbors._kde after scikit-learn==0.22. 
I also have problem with numpy version as shown below. My numpy is the latest one 1.20.1.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-cdf82bd1ee44> in <module>
----> 1 import ssam

C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\ssam\__init__.py in <module>
     35 from scipy.ndimage import zoom
     36 
---> 37 from .utils import corr, calc_ctmap, calc_corrmap, flood_fill, calc_kde
     38 
     39 def calc_slice(args):

ImportError: numpy.core.multiarray failed to import
```

In addition, I can do `import numpy.core.multiarray` in the same Jupyter notebook 1 line before `import ssam` and it gave me no error. Not sure why it doesn't work when doing `import ssam`

**Comment by pjb7687** [comment]
Hi, Thanks for reporting. I will update the 'requirements.txt' file including the versions that SSAM requires. Regarding the numpy problem, I guess when SSAM was being installed it would be linked aginst a different numpy available on your system. If you are using conda maybe you can try in a new environment? If it doesn't work would you mind posting the pip installation log? maybe I can find a clue there.

**Comment by lidanwu** [comment]
Thank you for the reply! I did try a new conda and downgraded my numpy to 1.19.5, python to 3.7.1, llvmlite to 0.35.0 in addition to change the __init__.py of ssam manually. All these together make `import ssam` works.
