### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by williamhsy** [eilslabs/ssam#18]
Hi,

Thanks for such a great tool. I was trying to install ssam using pip (`pip3 install git+https://github.com/HiDiHlabs/ssam.git`) but with the following error: 

> RuntimeError: Could not find a `llvm-config` binary

There is a related [post](https://github.com/numba/llvmlite/issues/621). But I am using pip v19.3.1, so I am guessing the error I encountered is not related to the version issue. I was wondering if you can help me to figure it out? Thanks.

**Comment by pjb7687** [comment]
Hi, I think that would be due to installing `numba` which is used by other packages e.g., `umap-learn`... I would like to suggest that perhaps you can install `numba` first with `conda`, and then use `pip` to install the rest?

**Comment by williamhsy** [comment]
Thanks so much for the quick reply. It works!!
