### ISSUE TITLE
MemoryError in run_kde

### ISSUE THREAD

**Issue by rlittman16** [eilslabs/ssam#2]
Hello,

I have gotten SSAM to work on a small subset of my dataset. I wanted to scale it up to a larger piece of the dataset and got the following error:
Traceback (most recent call last):
  File "SSAM_playground.py", line 199, in <module>
    analysis.run_kde(bandwidth=2.5, use_mmap=False)
  File "/u/home/r/rlittman/project-rlittman/miniconda3/lib/python3.7/site-packages/ssam/__init__.py", line 512, in run_kde
    vf = np.zeros(vf_shape)
MemoryError

I am on a cluster where I have allotted 128G which I would think would be more than enough. For reference I am using a window size of 2000x3000 and I have 9,952,329 points in my data. If this can't be resolved, is there any downside to tiling my data and processing on smaller pieces for kde? would I then be able to put them back together for downstream clustering and spatial domain analysis.

Thanks in advanced!

**Comment by pjb7687** [comment]
Hello,

Currently the maximum memory required by SSAM is roughly 2 x (width) x (height) x (depth) x (number of genes) x (size of double). Maybe you can try turning on mmap to reduce memory usage (but this will slow down your analysis). Other than mmap, I am testing other ways to reduce the memory usage by SSAM, but these are not implemented yet.

If you don't have enough memory to store the whole vector field in memory, then I would like to suggest selecting a subset of genes you have, e.g. selecting marker genes, and only use them for SSAM analysis.

**Comment by pjb7687** [comment]
Also, please double check whether you are running 64 bit Python. 32 bit Python cannot allocate memory more than 4 GB.

**Comment by rlittman16** [comment]
Thank you! I am using 64 bit, but the window size is too big. I can try requesting more memory. 

If I split up the data into pieces, how much would this affect the downstream analysis as long as I put it back together before spatial domain analysis?

**Comment by pjb7687** [comment]
If you split your data into pieces, I can imagine that the cluster centroids of the same cell type could be slightly different from each other.

Therefore, I would like to suggest that you can make a set of unified centroids by merging the centroids from pieces (e.g. identifying the same cell types and averaging it). And then, you can run SSAM again with each piece in 'guided mode' with the unified centroids. This will guarantee the same results in all different pieces.

**Comment by pjb7687** [comment]
Hi, I released dask branch which will handle the memory problem much better: https://github.com/eilslabs/ssam/tree/dask
