### ISSUE TITLE
normalize_vectors_sctransform() broadcasting problem

### ISSUE THREAD

**Issue by Xinrui0523** [eilslabs/ssam#6]
Hi, 

I'm trying to use ssam on my dataset, meeting the broadcasting problem when normalizing vectors with sctransform. 

The vec.shape=(9695, 321), while the norm_vec.shape = (9695, 320) after run_sctransfrom().
May I ask why and how to solve this problem?

Thanks & regards

**Comment by pjb7687** [comment]
Hi,

It seems like one of your genes is not so much expressed in your local maxima (expressed in less than 5 vectors), so I would like to firstly suggest lowering the threshold for selecting local maxima. Alternatively, you can force `sctransform` to use all genes:

```
normalize_vectors_sctransform(vst_kwargs={'min_cells': 1})
```

with the latest commit (41365a7d3a79563f8a39a8e301f3422e50dc2b04).
